# Generated by Django 6.0.3 on 2026-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.TextField(default='teste'),
        ),
    ]
